export default [
	{
		author: 'Larry McEnerney',
		title: 'The Craft of Writing Effectively',
		link: 'https://youtu.be/vtIzMaLkCaM',
		media: 'lecture, 1&nbsp;hr 21&nbsp;min',
		pullquote: null,
		comment:
			'I learned more about writing in these 80&nbsp;minutes than my entire schooling life, which conditioned me to believe writing is for demonstrating my own understanding. Bullshit.',
	},
	{
		author: 'Ze Frank',
		title: 'An Invocation for Beginnings',
		link: 'https://youtu.be/RYlCVwxoL_g',
		media: 'video, 3&nbsp;min',
		pullquote:
			'My pencils are sharp enough. Even the dull ones will make a mark.',
		comment:
			'We all get stuck between somewhere between zero and one now and again. When I’m in my deepest depths, I revisit Ze to start Getting Shit Done again.',
	},
	{
		author: 'John Green',
		title: 'The Anthropocene Reviewed',
		link: 'https://anthropocenereviewedbook.com',
		media: 'book',
		pullquote: null,
		comment: 'Learn to fall in love with the world again.',
	},
	{
		author: 'Merlin Mann',
		title: 'Merlin’s Wisdom Project',
		link: 'http://wisdom.limo',
		media: 'curated list',
		pullquote: 'Look for the chimneys.',
		comment: null,
	},
	{
		author: 'Matthew Butterick',
		title: 'Practical Typography',
		link: 'https://practicaltypography.com',
		media: 'digital book',
		pullquote: null,
		comment: 'The start of my journey with typography.',
	},
	{
		author: 'Marcin Wichary',
		title: 'The hardest working font in Manhattan',
		link: 'https://aresluna.org/the-hardest-working-font-in-manhattan',
		media: 'photo essay',
		pullquote: 'This is, perhaps, how you become gortonpilled.',
		comment: 'Marcin does it again, with… a love letter to a font?',
	},
	{
		author: 'Henry Desroches',
		title: 'A website to destroy all websites',
		link: 'https://henry.codes/writing/a-website-to-destroy-all-websites',
		media: 'essay (rant)',
		pullquote:
			'…a soullessly-regurgitated, compression-down-scaled, AI-up-scaled version version of the next.',
		comment:
			'Henry (<em>from online</em>) articulates in a way I couldn’t why this website exists.',
	},
	{
		author: 'Marcin Wichary',
		title: 'Crafting link underlines on Medium',
		link: 'https://medium.design/crafting-link-underlines-on-medium-7c03a9274f9',
		media: 'blog post',
		pullquote: null,
		comment: null,
	},
	{
		author: 'Steph Ango',
		title: 'Great tools choose to be bad at some things',
		link: 'https://stephanango.com/choose-to-be-bad',
		media: 'blog post',
		pullquote: 'Resist designing tools that are well-rounded.',
	},
	{
		author: 'Big Sky Software',
		title: 'The Grug-Brained Developer',
		link: 'https://grugbrain.dev',
		media: 'static site',
		pullquote: 'complexity <em>very</em>, <em>very</em> bad',
		comment: null,
	},
	{
		author: 'Tanizaki Jun’ichirō',
		title: 'In Praise of Shadows',
		link: 'https://www.goodreads.com/en/book/show/34473',
		media: 'essay',
		pullquote: null,
		comment: null,
	},
	{
		author: 'Patrick McKenzie',
		title: 'Falsehoods programmers believe about names',
		link: 'https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names',
		media: 'blog post',
		pullquote: '40.&nbsp;People have names.',
		comment:
			'Let us never again create a table with <code>first_name</code> and <code>last_name</code>.',
	},
	{
		author: 'Smith & Diction',
		title: 'Trust the Process',
		link: 'https://medium.com/smith-diction/trust-the-process-97ac8999d56a',
		media: 'essay',
		pullquote: 'There’s no secret sauce&nbsp;… and that’s awesome.',
		comment: null,
	},
	{
		author: 'Merlin Mann',
		title: 'Inbox Zero',
		link: 'https://youtu.be/z9UjeTMb3Yk',
		media: 'tech talk',
		pullquote: null,
		comment: 'I don’t think it means what you think it means.',
	},
	{
		author: 'Zoltan Hawryluk',
		title: 'Understanding Success Criterion&nbsp;6.1.1: Give a Shit',
		link: 'https://useragentman.com/wcag-wishlist',
		media: 'parody specification proposal',
		pullquote: 'Have some god-damned empathy for others.',
		comment: null,
	},
	{
		author: 'Robb Knight',
		title: 'The Web is Fantastic',
		link: 'https://rknight.me/blog/the-web-is-fantastic',
		media: 'blog post',
		pullquote:
			'Don’t give&nbsp;… these clowns your content. Don’t give them the time or your attention.',
		comment: null,
	},
	{
		author: 'Hank Green',
		title: 'We’re All Scared',
		link: 'https://youtu.be/fGmAekTPD5c',
		media: 'vlog, 4&nbsp;min',
		pullquote:
			'The only way I’ve found to temper the fear of creation is just to create, constantly.',
		comment: null,
	},
	{
		author: 'Oliver Reichenstein',
		title: 'Web Design is 95% Typography',
		link: 'https://ia.net/topics/the-web-is-all-about-typography-period',
		media: 'article, 4&nbsp;min',
		pullquote: null,
		comment: null,
	},
	{
		author: 'Oliver Reichenstein',
		title: 'Maker’s Knowledge',
		link: 'https://ia.net/topics/the-web-is-all-about-typography-period',
		media: 'article, 11&nbsp;min',
		pullquote:
			'<i>Design Thinking</i> suggests that there’s thought without design and design without thought.',
		comment: '“There isn’t.”',
	},
	{
		author: 'Matthias Endler',
		title: 'The Best Programmers I Know',
		link: 'https://endler.dev/2025/best-programmers',
		media: 'blog post',
		pullquote: null,
		comment: null,
	},
	// {
	// 	author: 'Nilay Patel',
	// 	title:
	// 		'Best printer 2023: just buy this Brother laser printer everyone has, it’s fine',
	// 	link: 'https://www.theverge.com/23642073/best-printer-2023-brother-laser-wi-fi-its-fine',
	// 	media: 'article',
	// 	pullquote: 'Never think about printers again.',
	// 	comment:
	// 		'Perhaps not life changing, but damned if Nilay’s subtext about AI slop isn’t on point.',
	// },
	// {
	// 	author: 'Merlin Mann',
	// 	title: 'Better',
	// 	link: 'http://www.merlinmann.com/better',
	// 	media: 'blog post?',
	// 	pullquote: null,
	// 	comment: null,
	// },
];
